# Generated by Django 5.2.4 on 2025-07-18 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='提供商名称')),
                ('base_url', models.URLField(help_text='API的基础URL，如：https://api.openai.com/v1', verbose_name='基础URL')),
                ('api_key', models.CharField(max_length=200, verbose_name='API密钥')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='额外请求头')),
                ('timeout', models.IntegerField(default=30, verbose_name='超时时间(秒)')),
                ('max_retries', models.IntegerField(default=3, verbose_name='最大重试次数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'API提供商',
                'verbose_name_plural': 'API提供商',
                'db_table': 'api_providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='APIProviderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='操作类型')),
                ('success', models.BooleanField(verbose_name='是否成功')),
                ('response_time', models.FloatField(null=True, verbose_name='响应时间(秒)')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('details', models.JSONField(default=dict, verbose_name='详细信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='apis.apiprovider')),
            ],
            options={
                'verbose_name': 'API提供商日志',
                'verbose_name_plural': 'API提供商日志',
                'db_table': 'api_provider_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
