# Generated by Django 5.2.4 on 2025-07-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiprovider',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='描述'),
        ),
    ]
