# Generated by Django 5.2.4 on 2025-07-18 04:30

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField(verbose_name='计费周期开始')),
                ('period_end', models.DateTimeField(verbose_name='计费周期结束')),
                ('total_requests', models.IntegerField(default=0, verbose_name='总请求数')),
                ('successful_requests', models.IntegerField(default=0, verbose_name='成功请求数')),
                ('failed_requests', models.IntegerField(default=0, verbose_name='失败请求数')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总tokens')),
                ('total_input_tokens', models.IntegerField(default=0, verbose_name='总输入tokens')),
                ('total_output_tokens', models.IntegerField(default=0, verbose_name='总输出tokens')),
                ('total_cost', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10, verbose_name='总成本')),
                ('input_cost', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10, verbose_name='输入成本')),
                ('output_cost', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10, verbose_name='输出成本')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('calculated', '已计算'), ('paid', '已支付'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '计费记录',
                'verbose_name_plural': '计费记录',
                'db_table': 'billing_records',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='CostAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=50, verbose_name='警告类型')),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='阈值')),
                ('current_value', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='当前值')),
                ('message', models.TextField(verbose_name='警告信息')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已解决')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
            ],
            options={
                'verbose_name': '成本警告',
                'verbose_name_plural': '成本警告',
                'db_table': 'cost_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('hour', models.IntegerField(blank=True, null=True, verbose_name='小时')),
                ('request_count', models.IntegerField(default=0, verbose_name='请求次数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功次数')),
                ('error_count', models.IntegerField(default=0, verbose_name='错误次数')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总tokens')),
                ('input_tokens', models.IntegerField(default=0, verbose_name='输入tokens')),
                ('output_tokens', models.IntegerField(default=0, verbose_name='输出tokens')),
                ('total_cost', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10, verbose_name='总成本')),
                ('avg_duration_ms', models.FloatField(default=0, verbose_name='平均耗时(毫秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '使用统计',
                'verbose_name_plural': '使用统计',
                'db_table': 'usage_statistics',
                'ordering': ['-date', '-hour'],
            },
        ),
        migrations.CreateModel(
            name='APIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='请求ID')),
                ('method', models.CharField(default='POST', max_length=10, verbose_name='请求方法')),
                ('endpoint', models.CharField(max_length=200, verbose_name='请求端点')),
                ('request_data', models.JSONField(default=dict, verbose_name='请求数据')),
                ('response_data', models.JSONField(default=dict, verbose_name='响应数据')),
                ('input_tokens', models.IntegerField(default=0, verbose_name='输入tokens')),
                ('output_tokens', models.IntegerField(default=0, verbose_name='输出tokens')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总tokens')),
                ('input_cost', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10, verbose_name='输入成本')),
                ('output_cost', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10, verbose_name='输出成本')),
                ('total_cost', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10, verbose_name='总成本')),
                ('status_code', models.IntegerField(verbose_name='响应状态码')),
                ('duration_ms', models.IntegerField(verbose_name='请求耗时(毫秒)')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('error_type', models.CharField(blank=True, max_length=100, verbose_name='错误类型')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='ai_models.aimodel')),
            ],
            options={
                'verbose_name': 'API请求记录',
                'verbose_name_plural': 'API请求记录',
                'db_table': 'api_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
