# Generated by Django 5.2.4 on 2025-07-18 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_models', '0001_initial'),
        ('billing', '0002_initial'),
        ('quotas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='quota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='quotas.userquota'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costalert',
            name='quota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_alerts', to='quotas.userquota'),
        ),
        migrations.AddField(
            model_name='costalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usagestatistics',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_statistics', to='ai_models.aimodel'),
        ),
        migrations.AddField(
            model_name='usagestatistics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_statistics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='apirequest',
            index=models.Index(fields=['user', 'created_at'], name='api_request_user_id_1213fa_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequest',
            index=models.Index(fields=['model', 'created_at'], name='api_request_model_i_281a6e_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequest',
            index=models.Index(fields=['status_code'], name='api_request_status__f5b5a7_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequest',
            index=models.Index(fields=['created_at'], name='api_request_created_ea1fe3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='billingrecord',
            unique_together={('user', 'quota', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='usagestatistics',
            index=models.Index(fields=['date'], name='usage_stati_date_a91746_idx'),
        ),
        migrations.AddIndex(
            model_name='usagestatistics',
            index=models.Index(fields=['user', 'date'], name='usage_stati_user_id_7cd359_idx'),
        ),
        migrations.AddIndex(
            model_name='usagestatistics',
            index=models.Index(fields=['model', 'date'], name='usage_stati_model_i_b03487_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usagestatistics',
            unique_together={('user', 'model', 'date', 'hour')},
        ),
    ]
