# Generated by Django 5.2.4 on 2025-07-18 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0002_change_pricing_to_per_1m'),
        ('billing', '0003_initial'),
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequest',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='ai_models.aimodel'),
        ),
        migrations.AlterField(
            model_name='apirequest',
            name='model_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='groups.modelgroup'),
        ),
        migrations.AlterField(
            model_name='usagestatistics',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_statistics', to='ai_models.aimodel'),
        ),
    ]
