# Generated by Django 5.2.4 on 2025-07-19 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0003_fix_provider_cascade'),
        ('billing', '0004_alter_apirequest_model_alter_apirequest_model_group_and_more'),
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='model_group_name',
            field=models.CharField(blank=True, help_text='保留的模型组名称', max_length=200, verbose_name='模型组名称'),
        ),
        migrations.AddField(
            model_name='apirequest',
            name='model_name',
            field=models.CharField(blank=True, help_text='保留的模型名称', max_length=200, verbose_name='模型名称'),
        ),
        migrations.AddField(
            model_name='apirequest',
            name='model_provider_name',
            field=models.CharField(blank=True, help_text='保留的提供商名称', max_length=200, verbose_name='提供商名称'),
        ),
        migrations.AlterField(
            model_name='apirequest',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='ai_models.aimodel'),
        ),
        migrations.AlterField(
            model_name='apirequest',
            name='model_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='groups.modelgroup'),
        ),
    ]
