# Generated by Django 5.2.4 on 2025-07-18 04:30

import apps.quotas.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('usage_80', '使用率达到80%'), ('usage_90', '使用率达到90%'), ('usage_95', '使用率达到95%'), ('expired', '配额已过期'), ('rate_limit', '速率限制触发')], max_length=20, verbose_name='警告类型')),
                ('message', models.TextField(verbose_name='警告信息')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已解决')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
            ],
            options={
                'verbose_name': '配额警告',
                'verbose_name_plural': '配额警告',
                'db_table': 'quota_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotaUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('consume', '消费'), ('add', '增加'), ('reset', '重置'), ('refund', '退款')], max_length=20, verbose_name='操作类型')),
                ('amount', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='变动金额')),
                ('remaining', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='剩余配额')),
                ('request_id', models.UUIDField(blank=True, null=True, verbose_name='请求ID')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '配额使用日志',
                'verbose_name_plural': '配额使用日志',
                'db_table': 'quota_usage_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(default=apps.quotas.models.generate_api_key, help_text='用于API调用的密钥，格式：sk-audit-{32位字符}', max_length=64, unique=True, verbose_name='API密钥')),
                ('total_quota', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总配额($)')),
                ('used_quota', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10, verbose_name='已使用配额($)')),
                ('period_type', models.CharField(choices=[('monthly', '按月'), ('daily', '按日'), ('weekly', '按周'), ('unlimited', '不限期')], default='monthly', max_length=20, verbose_name='配额周期')),
                ('period_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='周期开始时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('rate_limit_per_minute', models.IntegerField(blank=True, help_text='为空表示无限制', null=True, verbose_name='每分钟请求限制')),
                ('rate_limit_per_hour', models.IntegerField(blank=True, null=True, verbose_name='每小时请求限制')),
                ('rate_limit_per_day', models.IntegerField(blank=True, null=True, verbose_name='每日请求限制')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='自动续费')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('model_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quotas', to='groups.modelgroup')),
            ],
            options={
                'verbose_name': '用户配额',
                'verbose_name_plural': '用户配额',
                'db_table': 'user_quotas',
                'ordering': ['-created_at'],
            },
        ),
    ]
