# Generated by Django 5.2.4 on 2025-07-18 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userquota',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotausagelog',
            name='quota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='quotas.userquota'),
        ),
        migrations.AddField(
            model_name='quotaalert',
            name='quota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='quotas.userquota'),
        ),
        migrations.AlterUniqueTogether(
            name='userquota',
            unique_together={('user', 'model_group')},
        ),
    ]
