# Generated by Django 5.2.4 on 2025-07-18 09:57

import apps.quotas.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        ('quotas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquota',
            name='auto_renew',
        ),
        migrations.RemoveField(
            model_name='userquota',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='userquota',
            name='period_start',
        ),
        migrations.RemoveField(
            model_name='userquota',
            name='period_type',
        ),
        migrations.AlterField(
            model_name='quotaalert',
            name='alert_type',
            field=models.CharField(max_length=50, verbose_name='警告类型'),
        ),
        migrations.AlterField(
            model_name='quotausagelog',
            name='action',
            field=models.CharField(max_length=50, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='quotausagelog',
            name='amount',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='quotausagelog',
            name='request_id',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='请求ID'),
        ),
        migrations.AlterField(
            model_name='userquota',
            name='api_key',
            field=models.CharField(default=apps.quotas.models.generate_api_key, max_length=100, unique=True, verbose_name='API密钥'),
        ),
        migrations.AlterField(
            model_name='userquota',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='userquota',
            name='model_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotas', to='groups.modelgroup'),
        ),
        migrations.AlterField(
            model_name='userquota',
            name='rate_limit_per_day',
            field=models.IntegerField(default=86400, verbose_name='每日请求限制'),
        ),
        migrations.AlterField(
            model_name='userquota',
            name='rate_limit_per_hour',
            field=models.IntegerField(default=3600, verbose_name='每小时请求限制'),
        ),
        migrations.AlterField(
            model_name='userquota',
            name='rate_limit_per_minute',
            field=models.IntegerField(default=60, verbose_name='每分钟请求限制'),
        ),
        migrations.AlterField(
            model_name='userquota',
            name='total_quota',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='总配额($)'),
        ),
        migrations.AddIndex(
            model_name='quotaalert',
            index=models.Index(fields=['quota', 'created_at'], name='quota_alert_quota_i_7e50a9_idx'),
        ),
        migrations.AddIndex(
            model_name='quotaalert',
            index=models.Index(fields=['alert_type'], name='quota_alert_alert_t_b8dafb_idx'),
        ),
        migrations.AddIndex(
            model_name='quotaalert',
            index=models.Index(fields=['is_resolved'], name='quota_alert_is_reso_e5cd72_idx'),
        ),
        migrations.AddIndex(
            model_name='quotausagelog',
            index=models.Index(fields=['quota', 'created_at'], name='quota_usage_quota_i_d389c3_idx'),
        ),
        migrations.AddIndex(
            model_name='quotausagelog',
            index=models.Index(fields=['action'], name='quota_usage_action_c61042_idx'),
        ),
        migrations.AddIndex(
            model_name='userquota',
            index=models.Index(fields=['user', 'model_group'], name='user_quotas_user_id_2cdc9c_idx'),
        ),
        migrations.AddIndex(
            model_name='userquota',
            index=models.Index(fields=['api_key'], name='user_quotas_api_key_cd9e70_idx'),
        ),
        migrations.AddIndex(
            model_name='userquota',
            index=models.Index(fields=['created_at'], name='user_quotas_created_c721ce_idx'),
        ),
    ]
