# Generated by Django 5.2.4 on 2025-07-18 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        ('quotas', '0003_remove_period_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userquota',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userquota',
            name='description',
            field=models.TextField(blank=True, help_text='配额包的详细描述', verbose_name='配额描述'),
        ),
        migrations.AddField(
            model_name='userquota',
            name='name',
            field=models.CharField(default='migrate', help_text='配额包名称，如"高级开发包"、"基础套餐"等', max_length=100, verbose_name='配额名称'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='userquota',
            index=models.Index(fields=['name'], name='user_quotas_name_46cf81_idx'),
        ),
    ]
