# Generated by Django 5.2.4 on 2025-07-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotas', '0004_alter_userquota_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquota',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='软删除时间，为空表示未删除', null=True, verbose_name='删除时间'),
        ),
    ]
