# Generated by Django 5.2.4 on 2025-07-19 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        ('quotas', '0005_userquota_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquota',
            name='model_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='groups.modelgroup'),
        ),
    ]
