# Generated by Django 5.2.4 on 2025-07-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelGroupUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_count', models.IntegerField(default=0, verbose_name='请求次数')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总token数')),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='总成本')),
                ('date', models.DateField(verbose_name='日期')),
                ('hour', models.IntegerField(blank=True, null=True, verbose_name='小时')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '模型组使用日志',
                'verbose_name_plural': '模型组使用日志',
                'db_table': 'model_group_usage_logs',
                'ordering': ['-date', '-hour'],
            },
        ),
        migrations.CreateModel(
            name='ModelGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='组名称')),
                ('description', models.TextField(blank=True, verbose_name='组描述')),
                ('default_quota', models.DecimalField(blank=True, decimal_places=2, help_text='为该组分配给新用户的默认配额', max_digits=10, null=True, verbose_name='默认配额($)')),
                ('is_public', models.BooleanField(default=False, help_text='公开组所有用户都能看到', verbose_name='是否公开')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ai_models', models.ManyToManyField(blank=True, related_name='groups', to='ai_models.aimodel', verbose_name='包含模型')),
            ],
            options={
                'verbose_name': '模型组',
                'verbose_name_plural': '模型组',
                'db_table': 'model_groups',
                'ordering': ['name'],
            },
        ),
    ]
