# Generated by Django 5.2.4 on 2025-07-18 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_models', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modelgroup',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='accessible_groups', to=settings.AUTH_USER_MODEL, verbose_name='允许访问的用户'),
        ),
        migrations.AddField(
            model_name='modelgroupusagelog',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='groups.modelgroup'),
        ),
        migrations.AddField(
            model_name='modelgroupusagelog',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_models.aimodel'),
        ),
        migrations.AddField(
            model_name='modelgroupusagelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='modelgroupusagelog',
            unique_together={('group', 'user', 'model', 'date', 'hour')},
        ),
    ]
