# Generated by Django 5.2.4 on 2025-07-18 04:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('display_name', models.CharField(max_length=100, verbose_name='显示名称')),
                ('description', models.TextField(blank=True, verbose_name='模型描述')),
                ('input_price_per_1k', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10, verbose_name='输入价格($/1k tokens)')),
                ('output_price_per_1k', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10, verbose_name='输出价格($/1k tokens)')),
                ('context_length', models.IntegerField(default=4096, verbose_name='上下文长度')),
                ('max_output_tokens', models.IntegerField(blank=True, null=True, verbose_name='最大输出tokens')),
                ('capabilities', models.JSONField(default=dict, help_text='如：{"vision": true, "function_calling": true}', verbose_name='能力特性')),
                ('model_type', models.CharField(choices=[('text', '文本生成'), ('chat', '对话模型'), ('embedding', '嵌入模型'), ('image', '图像生成'), ('multimodal', '多模态')], default='chat', max_length=50, verbose_name='模型类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可用')),
                ('external_id', models.CharField(blank=True, max_length=200, verbose_name='外部ID')),
                ('last_updated_from_api', models.DateTimeField(blank=True, null=True, verbose_name='最后从API更新')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='apis.apiprovider', verbose_name='API提供商')),
            ],
            options={
                'verbose_name': 'AI模型',
                'verbose_name_plural': 'AI模型',
                'db_table': 'ai_models',
                'ordering': ['provider__name', 'name'],
                'unique_together': {('provider', 'name')},
            },
        ),
    ]
