# Generated by Django 5.2.4 on 2025-07-19 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0002_change_pricing_to_per_1m'),
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='provider',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='models', 
                to='apis.apiprovider', 
                verbose_name='API提供商'
            ),
        ),
    ]
